FROM plugins/base:{{ if UseMultiArch }}mulitarch{{ else }}linux-arm{{ end }}

LABEL maintainer="{{ DockerMaintainer }}" \
  org.label-schema.name="{{ DockerSchemaName }}" \
  org.label-schema.vendor="{{ DockerSchemaVendor }}" \
  org.label-schema.schema-version="1.0"

ADD release/linux/arm/{{ Executable }} /bin/
ENTRYPOINT [ "/bin/{{ Executable }}" ]
