FROM plugins/base:multiarch

LABEL maintainer="{{ DockerMaintainer }}" \
  org.label-schema.name="{{ DockerSchemaName }}" \
  org.label-schema.vendor="{{ DockerSchemaVendor }}" \
  org.label-schema.schema-version="{{ DockerSchemaVersion }}"

ADD release/linux/arm64/{{ Executable }} /bin/
ENTRYPOINT ["/bin/{{ Executable }}"]
