FROM plugins/base:{{ if UseMultiArch }}mulitarch{{ else }}linux-amd64{{ end }}

LABEL maintainer="{{ DockerMaintainer }}" \
  org.label-schema.name="{{ DockerSchemaName }}" \
  org.label-schema.vendor="{{ DockerSchemaVendor }}" \
  org.label-schema.schema-version="1.0"

ADD release/linux/amd64/{{ Executable }} /bin/
ENTRYPOINT [ "/bin/{{ Executable }}" ]
